# Generated by Django 4.1.2 on 2022-12-10 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('cost_per_unit', models.IntegerField(blank=True, null=True)),
                ('length_in_days', models.IntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Subscription',
            },
        ),
        migrations.CreateModel(
            name='UserPaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('days_for_next_payment', models.IntegerField(blank=True, null=True)),
                ('bill_at_end_of_cycle', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment History',
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('card_expiry', models.DateField(blank=True, null=True)),
                ('card_cvv_code', models.CharField(blank=True, max_length=3, null=True)),
                ('active_membership', models.BooleanField(default=True)),
                ('billing_boolean', models.BooleanField(blank=True, default=True, null=True)),
                ('membership_plan', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplans')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
